[package]
workspace = "../.."
name = "p1-client"
version = "0.0.0"
publish = false
edition = "2018"

[[bin]]
name = "client"
path = "main.rs"

[dependencies]
websocket = "0.22.3"
gfx = "0.18.0"
gfx_window_glutin = "0.30.0"
glutin = "0.20.0"
cgmath = "0.17.0"
